version: '2'
services:
  location-ms:
    image: cdtafurd/location-ms_location-ms:back2
    ports:
    - 3000:3000/tcp
  location-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: location_db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: root
    ports:
    - 3306:3306/tcp